### ISSUE TITLE
Using docker on windows,sucessfull image download at windows but error at execution

### ISSUE THREAD

**Issue by tarunkumard** [denvazh/gatling#22]
Getting below message at docker console,my user files in windows 10 machine is here 
C:\PerfTools\Gatling\gatling-charts-highcharts-bundle-3.0.0-bundle\gatling-charts-highcharts-bundle-3.0.0\user-files

why docker unable to find it?please guide me

dast@WS-124157L MINGW64 /c/Program Files/Docker Toolbox
$ docker run -it --rm -v /home/core/gatling/conf:/opt/gatling/conf \
> -v /home/core/gatling/user-files:/opt/gatling/user-files \
> -v /home/core/gatling/results:/opt/gatling/results \
> denvazh/gatling
GATLING_HOME is set to /opt/gatling
15:17:27.730 [main] DEBUG io.gatling.compiler.ZincCompiler$ - Full compilation, no sources in previous analysis.
15:17:27.978 [main] DEBUG io.gatling.compiler.ZincCompiler$ - Compilation successful
15:17:30.132 [main] INFO io.gatling.core.config.GatlingConfiguration$ - Gatling will try to use 'gatling.conf' as custom config file.
15:17:31.757 [GatlingSystem-akka.actor.default-dispatcher-2] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
There is no simulation script. Please check that your scripts are in user-files/simulations

**Comment by denvazh** [comment]
Hi! Sorry for taking a while to follow-up! It is a bit hard for me to fully reproduce it as I don't really use Windows. After doing quick investigation on how docker handles shared drives and make them available to the linux containers it seems issue could be either with how you specify/use shared volumes: https://docs.docker.com/docker-for-windows/#shared-drives .

**Comment by tarunkumard** [comment]
sure
