### ISSUE TITLE
consider using ENTRYPOINT for gatling.sh

### ISSUE THREAD

**Issue by cskinfill** [denvazh/gatling#3]
I believe if you use `ENTRYPOINT ["gating.sh"]` it will allow someone to pass arguments to the gatling.sh script.

**Comment by denvazh** [comment]
Thank you for the suggestion! When I was writing initial configuration, I didn't need to pass arguments, thus I didn't know about them. I will adjust `Dockerfile` to use `ENTRYPOINT ` and allow the following arguments to be passed: https://github.com/gatling/gatling/blob/master/gatling-app/src/main/scala/io/gatling/app/cli/ArgsParser.scala

**Comment by denvazh** [comment]
Fixed in #4
