### ISSUE TITLE
Can reduce image size by 20%

### ISSUE THREAD

**Issue by so0k** [denvazh/gatling#8]
Please remove temporary data under `/tmp/` in same RUN command

[Unzipped, but not removed](https://github.com/denvazh/gatling/blob/a1469dde0a32241e97e805bdd6871b86b1b1de9e/2.2.2/Dockerfile#L25)

**Comment by so0k** [comment]
```
vincentdesmet/gatling                     2.2.2               2 minutes ago       217.6 MB
denvazh/gatling                           2.2.2               6 weeks ago         281.2 MB
```

**Comment by denvazh** [comment]
Thank you! Good catch. I will adjust scripts to clear `/tmp` directory.
